import{a as f,S as h,i as d}from"./assets/vendor-4d51048b.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))n(s);new MutationObserver(s=>{for(const a of s)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(s){const a={};return s.integrity&&(a.integrity=s.integrity),s.referrerPolicy&&(a.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?a.credentials="include":s.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(s){if(s.ep)return;s.ep=!0;const a=r(s);fetch(s.href,a)}})();const u=async(o,e)=>{const r={params:{key:"43212506-95870309335e8ebf3ea9c8656",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}};return await f.get("https://pixabay.com/api",r)},p=o=>o.map(e=>`
      <li class="gallery-item"><a href="${e.largeImageURL}" class="gallery-link"><img src="${e.webformatURL}"
            alt="${e.tags}" class="gallery-img"></a>
        <div class="card-content">
          <div class="label-cont"><span class="label">Likes</span><span class="value">${e.likes}</span></div>
          <div class="label-cont"><span class="label">Views</span><span class="value">${e.views}</span></div>
          <div class="label-cont"><span class="label">Comments</span><span class="value">${e.comments}</span>
          </div>
          <div class="label-cont"><span class="label">Downloads</span><span class="value">${e.downloads}</span></div>
        </div>
      </li>
      `).join(""),t={searchForm:document.querySelector(".search-form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadButton:document.querySelector(".load-button")},m={noMatches(){d.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#EF4040",position:"topRight"})},loadsLimit(){d.show({message:"We are sorry, but you have reached the end of search results.",messageColor:"#fff",backgroundColor:"#0099FF",position:"topRight"})}},y={captionsData:"alt",captionDelay:250},g=new h(".gallery a",y);let l=null,c=null;const v=async o=>{o.preventDefault(),l=1,t.gallery.innerHTML="",t.loader.classList.add("is-visible"),t.loadButton.classList.remove("is-visible"),c=o.srcElement.elements.search_input.value;try{const e=await u(c,l),{data:r}=e;if(r.hits.length===0){m.noMatches();return}t.loader.classList.remove("is-visible"),t.gallery.innerHTML=p(r.hits),t.loadButton.classList.add("is-visible"),g.refresh()}catch(e){t.loader.classList.remove("is-visible"),console.log(e)}},b=async()=>{const o=document.querySelector(".gallery-item").getBoundingClientRect();l++,t.loadButton.classList.remove("is-visible"),t.loader.classList.add("is-visible");try{const e=await u(c,l),{data:r}=e;if(console.log(e),t.loader.classList.remove("is-visible"),t.gallery.insertAdjacentHTML("beforeend",p(r.hits)),g.refresh(),scrollBy({top:o.height*2,behavior:"smooth"}),e.config.params.page*e.config.params.per_page>=r.totalHits){m.loadsLimit();return}t.loadButton.classList.add("is-visible")}catch(e){t.loader.classList.remove("is-visible"),console.log(e)}};t.searchForm.addEventListener("submit",v);t.loadButton.addEventListener("click",b);
//# sourceMappingURL=commonHelpers.js.map
