import{a as f,S as h,i as u}from"./assets/vendor-4d51048b.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const n of a.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(t){if(t.ep)return;t.ep=!0;const a=o(t);fetch(t.href,a)}})();const p=async(r,e)=>{const o={params:{key:"43212506-95870309335e8ebf3ea9c8656",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}};return await f.get("https://pixabay.com/api",o)},m=r=>r.map(e=>`
      <li class="gallery-item"><a href="${e.largeImageURL}" class="gallery-link"><img src="${e.webformatURL}"
            alt="${e.tags}" class="gallery-img"></a>
        <div class="card-content">
          <div class="label-cont"><span class="label">Likes</span><span class="value">${e.likes}</span></div>
          <div class="label-cont"><span class="label">Views</span><span class="value">${e.views}</span></div>
          <div class="label-cont"><span class="label">Comments</span><span class="value">${e.comments}</span>
          </div>
          <div class="label-cont"><span class="label">Downloads</span><span class="value">${e.downloads}</span></div>
        </div>
      </li>
      `).join(""),s={searchForm:document.querySelector(".search-form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadButton:document.querySelector(".load-button")},c={noMatches(){u.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#EF4040",position:"topRight"})},loadsLimit(){u.show({message:"We are sorry, but you have reached the end of search results.",messageColor:"#fff",backgroundColor:"#0099FF",position:"topRight"})}},y={captionsData:"alt",captionDelay:250},g=new h(".gallery a",y);let l=null,d=null;const v=async r=>{r.preventDefault(),l=1,s.gallery.innerHTML="",s.loader.classList.add("is-visible"),s.loadButton.classList.remove("is-visible"),d=r.srcElement.elements.search_input.value;try{const e=await p(d,l),{data:o}=e;if(s.loader.classList.remove("is-visible"),o.hits.length===0){c.noMatches();return}if(s.gallery.innerHTML=m(o.hits),g.refresh(),o.totalHits<=15){c.loadsLimit();return}s.loadButton.classList.add("is-visible")}catch(e){s.loader.classList.remove("is-visible"),console.log(e)}},b=async()=>{const r=document.querySelector(".gallery-item").getBoundingClientRect();l++,s.loadButton.classList.remove("is-visible"),s.loader.classList.add("is-visible");try{const e=await p(d,l),{data:o}=e;if(s.loader.classList.remove("is-visible"),s.loadButton.classList.add("is-visible"),s.gallery.insertAdjacentHTML("beforeend",m(o.hits)),g.refresh(),scrollBy({top:r.height*2,behavior:"smooth"}),e.config.params.page*e.config.params.per_page>=o.totalHits){c.loadsLimit(),s.loadButton.classList.remove("is-visible");return}}catch(e){s.loader.classList.remove("is-visible"),console.log(e)}};s.searchForm.addEventListener("submit",v);s.loadButton.addEventListener("click",b);
//# sourceMappingURL=commonHelpers.js.map
