import{a as f,S as h,i as u}from"./assets/vendor-4d51048b.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&d(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const p=(a,e)=>{const r={params:{key:"43212506-95870309335e8ebf3ea9c8656",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}};return f.get("https://pixabay.com/api",r)},m=a=>a.map(e=>`
      <li class="gallery-item"><a href="${e.largeImageURL}" class="gallery-link"><img src="${e.webformatURL}"
            alt="${e.tags}" class="gallery-img"></a>
        <div class="card-content">
          <div class="label-cont"><span class="label">Likes</span><span class="value">${e.likes}</span></div>
          <div class="label-cont"><span class="label">Views</span><span class="value">${e.views}</span></div>
          <div class="label-cont"><span class="label">Comments</span><span class="value">${e.comments}</span>
          </div>
          <div class="label-cont"><span class="label">Downloads</span><span class="value">${e.downloads}</span></div>
        </div>
      </li>
      `).join(""),s={searchForm:document.querySelector(".search-form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadButton:document.querySelector(".load-button")},n={noMatches(){u.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#EF4040",position:"topRight"})},loadsLimit(){u.show({message:"We are sorry, but you have reached the end of search results.",messageColor:"#fff",backgroundColor:"#0099FF",position:"topRight"})}},y={captionsData:"alt",captionDelay:250},g=new h(".gallery a",y);let l=null,c=null;const v=async a=>{try{a.preventDefault(),l=1,s.gallery.innerHTML="",s.loader.classList.add("is-visible"),s.loadButton.classList.remove("is-visible"),c=a.srcElement.elements.search_input.value;const e=await p(c,l),{data:r}=e;if(s.loader.classList.remove("is-visible"),r.hits.length===0){n.noMatches();return}if(s.gallery.innerHTML=m(r.hits),g.refresh(),r.totalHits<=15){n.loadsLimit();return}s.loadButton.classList.add("is-visible")}catch(e){s.loader.classList.remove("is-visible"),console.log(e)}},b=async()=>{try{const a=document.querySelector(".gallery-item").getBoundingClientRect();l++,s.loadButton.classList.remove("is-visible"),s.loader.classList.add("is-visible");const e=await p(c,l),{data:r}=e;if(s.loader.classList.remove("is-visible"),s.loadButton.classList.add("is-visible"),s.gallery.insertAdjacentHTML("beforeend",m(r.hits)),g.refresh(),scrollBy({top:a.height*2,behavior:"smooth"}),e.config.params.page*e.config.params.per_page>=r.totalHits){n.loadsLimit(),s.loadButton.classList.remove("is-visible");return}}catch(a){s.loader.classList.remove("is-visible"),console.log(a)}};s.searchForm.addEventListener("submit",v);s.loadButton.addEventListener("click",b);
//# sourceMappingURL=commonHelpers.js.map
